name: Fetch YouBike Data

on:
  schedule:
    - cron: '*/10 * * * *' # 每 10 分鐘執行一次
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Clean pip cache
        run: pip cache purge
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.14
      - name: Install dependencies
        # 安裝 requirements.txt，不會拉 pyarrow
        run: | 
          python -m pip install --upgrade pip
          pip install  pandas==1.5.3 matplotlib requests
      - name: Fetch YouBike data
        run: python fetch_and_process.py
      # - name: Commit & Push CSV
      #   run: |
      #     git config user.name "github-actions"
      #     git config user.email "actions@github.com"
      #     git add data/youbike_data.csv
      #     git commit -m "Update YouBike CSV"
      #     git push
